trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

variables:
  - name: _RunAsPublic
    value: true

  - ? ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}
    : - group: DotNet-MeastroApi-Access
      - group: DotNet-SignApi-Access

stages:
  - stage: build
    displayName: 'Build'
    jobs:
      - job: Windows_NT
        pool:
          vmImage: 'windows-latest'
        displayName: 'Windows_NT Build_Release'
        timeoutInMinutes: 90
        workspace:
          clean: all
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
            ${{ if eq(variables._RunAsPublic, True) }}:
              Build_Debug:
                _BuildConfig: Debug
        steps:
          - checkout: self
            clean: true
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK 3.1.201'
            inputs:
              packageType: 'sdk'
              version: '3.1.201'
          - powershell: eng/common/build.ps1
              -restore
              -build
              -test
              -pack
              -publish
              -configuration $(_BuildConfig)
              -ci
              -officialbuild
            displayName: 'Windows Build / Publish'
            env:
              MAESTRO_APIKEY: $(MAESTRO_APIKEY)
              SIGNING_AUTH_TOKEN: $(SIGNING_AUTH_TOKEN)
          - publish: '_build/log/$(_BuildConfig)'
            artifact: 'Logs_Build_$(Agent.OS)_$(_BuildConfig)'
            displayName: 'Publish Logs'
            continueOnError: true
            condition: always()